# fly.toml app configuration file generated for guesty-booking-experts-integration on 2025-08-29T07:01:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'guesty-booking-experts-integration'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[env]
  PYTHONPATH = "/app/app"  
  SQLITE_DB_PATH = "/data/database.db"

[processes]
  worker = "python -m app.workers.calendar_worker"

[[mounts]]
  source = "data"
  destination = "/data"
  processes = ['app','worker']