# fly.toml app configuration file generated for guesty-booking-experts-integration on 2025-08-29T07:01:52Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'guesty-booking-experts-integration'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
  memory = '2gb'
  cpu_kind = 'performance'
  cpus = 4
  memory_mb = 8192

[env]
  PYTHONPATH = "/app/app"
